name: nf-dock

channels:
    - conda-forge
    - bioconda
    - omnia

dependencies:
    - python==3.12
    - pip
    # ── Docking ──
    # - bioconda::gnina>=1.3
    - conda-forge::fpocket
    - conda-forge::openbabel  # mol format conversions
    # ── Structure prep ──
    - conda-forge::pdbfixer
    - conda-forge::openssl
    - conda-forge::unzip
    # utils
    - conda-forge::cmake 
    - conda-forge::cuda-toolkit
    - conda-forge::cuda-nvtx-dev
    - conda-forge::cuda-nvcc
    - conda-forge::libboost
    - conda-forge::jsoncpp
    - conda-forge::libprotobuf
    - conda-forge::protobuf
    - conda-forge::hdf5
    - conda-forge::glog
    - conda-forge::zlib
    - bioconda::atlas
    - omnia::eigen3
    - pip:
        - biopython
        - pdb-tools
        - numpy
        - pandas
        - rdkit
        - scikit-learn
        - 'multiqc>=1.21'
        - --extra-index-url https://pypi.ngc.nvidia.com
