name: nf-env

channels:
    - conda-forge
    - bioconda

dependencies:
    - python==3.12
    - pip
    # ── Docking ──
    - bioconda::gnina>=1.3
    - conda-forge::fpocket
    - conda-forge::openbabel  # mol format conversions
    # ── Structure prep ──
    - conda-forge::pdbfixer
    - conda-forge::openssl
    - conda-forge::unzip
    - pip:
        - biopython
        - pdb-tools
        - numpy
        - pandas
        - rdkit
        - scikit-learn
        - 'multiqc>=1.21'
