name: nf-dock

channels:
    - conda-forge
    - bioconda

dependencies:
    - python>=3.10
    - pip
    # ── Docking ──
    - conda-forge::fpocket
    - conda-forge::openbabel>=3.0  # mol format conversions
    # ── Structure prep ──
    - conda-forge::pdbfixer
    - conda-forge::openssl
    - conda-forge::unzip
    - pip:
        - biopython
        - pdb-tools
        # - numpy
        # - pandas
        - rdkit
        - scikit-learn
        - 'multiqc>=1.21'
